name: 'Read File Content'
author: 'Kenny Wong'
description: 'Read file contents. You can also get the file content in the branch'
inputs:
  token:
    description: 'Your GITHUB_TOKEN'
    default: ${{ github.token }}
    required: false
  path:
    description: 'File to be replaced'
    default: ''
    required: false
  localfile:
    description: 'Local File path'
    default: ''
    required: false
  branch:
    description: 'The person that committed the file. Default: the authenticated user.'
    default: ${{ github.ref_name }}
    required: false

outputs:
  content:
    description: 'file content'
  size:
    description: 'file size'
  type:
    description: ''
  encoding:
    description: ''
  name:
    description: ''
  path:
    description: ''
  sha:
    description: ''
  url:
    description: ''
  git_url:
    description: ''
  html_url:
    description: ''
  download_url:
    description: ''
  target:
    description: ''
  submodule_git_url:
    description: ''

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'file'
  color: 'purple'
