name: test
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install
      - run: npm run build
      - run: mkdir -p build

      - name: Read README.md
        id: package
        # uses: jaywcjlove/github-action-read-file@main
        uses: ./
        with:
          path: package.json

      - name: Echo package.json
        run: echo "${{ steps.package.outputs.content }}"

      - name: Read src/index.ts
        id: tsfile
        # uses: jaywcjlove/github-action-read-file@main
        uses: ./
        with:
          path: src/index.ts

      - name: Echo (content) src/index.ts
        run: echo "${{ steps.tsfile.outputs.content }}"
      - name: Echo (size) src/index.ts
        run: echo "${{ steps.tsfile.outputs.size }}"
      - name: Echo (type) src/index.ts
        run: echo "${{ steps.tsfile.outputs.type }}"
      - name: Echo (encoding) src/index.ts
        run: echo "${{ steps.tsfile.outputs.encoding }}"
      - name: Echo (name) src/index.ts
        run: echo "${{ steps.tsfile.outputs.name }}"
      - name: Echo (path) src/index.ts
        run: echo "${{ steps.tsfile.outputs.path }}"
      - name: Echo (sha) src/index.ts
        run: echo "${{ steps.tsfile.outputs.sha }}"
      - name: Echo (url) src/index.ts
        run: echo "${{ steps.tsfile.outputs.url }}"
      - name: Echo (git_url) src/index.ts
        run: echo "${{ steps.tsfile.outputs.git_url }}"
      - name: Echo (html_url) src/index.ts
        run: echo "${{ steps.tsfile.outputs.html_url }}"
      - name: Echo (download_url) src/index.ts
        run: echo "${{ steps.tsfile.outputs.download_url }}"
      - name: Echo (target) src/index.ts
        run: echo "${{ steps.tsfile.outputs.target }}"
      - name: Echo (submodule_git_url) src/index.ts
        run: echo "${{ steps.tsfile.outputs.submodule_git_url }}"

      - name: Read README.md(gh-pages)
        id: ghpages
        # uses: jaywcjlove/github-action-read-file@main
        uses: ./
        with:
          branch: gh-pages
          path: README.md

      - name: Read src/index.ts
        id: tsfile2
        # uses: jaywcjlove/github-action-read-file@main
        uses: ./
        with:
          localfile: src/index.ts

      - name: Echo (content) src/index.ts
        run: echo "${{ steps.tsfile2.outputs.content }}"

      - name: Echo README.md(gh-pages)
        run: echo "${{ steps.ghpages.outputs.content }}"

      - name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          output: build/index.html
          github-corners: https://github.com/jaywcjlove/github-action-read-file
          favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🏷️</text></svg>

      - name: gh-pages README.md
        working-directory: build
        run: |
          cat > README.md << EOF
          Website: https://jaywcjlove.github.io/github-action-read-file  
          EOF

      - name: Is a tag/release created auto? 
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          # test: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
          package-path: ./package.json

      - name: get tag version
        id: tag_version
        uses: jaywcjlove/changelog-generator@main

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          commit_message: ${{steps.tag_version.outputs.tag}} ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@main
        with:
          head-ref: ${{steps.create_tag.outputs.version}}
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: Create Release
        uses: jaywcjlove/create-tag-action@main
        with:
          # test: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
          package-path: ./package.json
          release: true
          body: |
            Documentation ${{ steps.changelog.outputs.tag }}: https://raw.githack.com/jaywcjlove/github-action-read-file/${{ steps.changelog.outputs.gh-pages-short-hash }}/index.html  
            Comparing Changes: ${{ steps.changelog.outputs.compareurl }} 

            ${{ steps.changelog.outputs.changelog }}


            ```yml
            - name: Read README.md
              id: package
              uses: jaywcjlove/github-action-read-file@main
              with:
                path: package.json

            - name: Echo package.json
              run: echo "$\{{ steps.package.outputs.content }}"
            ```

            Specify the **branch** to read the file content

            ```yml
            - name: Read README.md(gh-pages)
              id: ghpages
              uses: jaywcjlove/github-action-read-file@main
              with:
                branch: gh-pages
                path: README.md

            - name: Echo README.md(gh-pages)
              run: echo "$\{{ steps.ghpages.outputs.content }}"
            ```
