name: test
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install
      - run: npm run build
      - run: mkdir -p build

      - name: Read README.md
        id: package
        # uses: jaywcjlove/github-action-read-file@main
        uses: ./
        with:
          path: package.json

      - name: Echo package.json
        run: echo "${{ steps.package.outputs.content }}"

      - name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          output: build/index.html
          github-corners: https://github.com/jaywcjlove/github-action-read-file
          favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🏷️</text></svg>
